# Specifies which previous versions should be kept in Dependency-Track when 
# a new version is uploaded.
# Possible values: NONE/MAJOR/MINOR/PATCH/SUFFIX/BUILD
#
# Also available as dtrack.keepPreviousVersions property/environment variable
keepPreviousVersions: MAJOR

# Skip projects whose artifactIds contain any of specified comma-separated strings
#
# Also available as dtrack.excludedProjects property/environment variable
excludedProjects: 
  - -tests
  - -demo

npmDependencies:

  # Extract additional NPM dependencies from annotations
  - annotationClassName: com.vaadin.flow.component.dependency.NpmPackage
    annotationPackageNameField: value
    annotationVersionField: version
