---
title: Installing Vaadin Charts for Flow
order: 2
layout: page
---

[[charts.installing]]
= Installing Vaadin Charts for Flow

As with most components for Vaadin Flow, you can install Vaadin Charts for Flow as a Maven dependency in your project.

Using Vaadin Charts requires a license key, which will be prompted on development time after 24 hours of the first time the application with Vaadin Charts is opened.

[[charts.installing.maven]]
== Maven Dependency

Install vaadin-charts by adding the dependency to the project (here as a Maven dependency in pom.xml):

[source,xml]
----
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-charts-flow</artifactId>
</dependency>
----

You do not need to specify the version number as long as you have vaadin-bom imported. Otherwise add

[source,xml]
----
<version>6.0.0</version>
----

Update the version number to the one you want

You also need to define the Vaadin add-ons repository if not already defined:

[source,xml]
----
<repository>
   <id>vaadin-addons</id>
   <url>https://maven.vaadin.com/vaadin-addons</url>
</repository>
----


[[charts.installing.license]]
== Installing a License Key

You need to have a valid license in order to develop your application with Vaadin Charts. 24 hours after you open the application with Vaadin Charts in a local browser, you will see a pop-up that asks you to validate your subscription.
This popup will open a new tab where you will have to login using your Vaadin account.
If the license is valid, it will be saved to the local storage of the browser and you will not see the pop-up again.

More information can be found at <<dummy/../../../bakeryflow/validating-license.asciidoc#,"Validating Vaadin Subscription">>.
