---
title: Overview
order: 1
layout: page
---

[[board.overview]]
= Overview

The [elementname]#vaadin-board# is a Polymer element for creating flexible responsive layouts and building nice looking dashboards.
The [elementname]#vaadin-board# key feature is how it effectively reorders the widgets on different screen sizes, maximizing the use of space and looking stunning.
Vaadin Board is using link:https://github.com/polymer/polymer/tree/2.0-preview[Polymer 2].

= Features

- Allows to divide you layout into regions by using [elementname]#vaadin-board-row#.
- Layout is responsive - rearranges child elements based on available space.
- Supports nested regions.

= Limitations

- Because non-chrome browsers need to load a polyfill, you can see flickering, before definition of the web component comes in.
You can suspend rendering the component before it is ready by adding the `unresolved` attribute in body:

[source, html]
----
  <body unresolved>
   //Your code here
  </body>
----

- Because Vaadin Board uses flexbox, there is a limited support for IE11.
If you want to have a border for the direct child of the [elementname]#vaadin-board-row# you need to create a wrapper
[elementname]#div# and add a border there, but not to the direct child of the [elementname]#vaadin-board-row#.
The description of the bug can be found link:https://github.com/philipwalton/flexbugs#7-flex-basis-doesnt-account-for-box-sizingborder-box[here].

