---
title: Overview
order: 1
layout: page
---

[[board.overview]]
= Overview

The [elementname]#vaadin-board# is a Polymer element for creating flexible responsive layouts and building nice looking dashboards.
The [elementname]#vaadin-board# key feature is how it effectively reorders the widgets on different screen sizes, maximizing the use of space and looking stunning.
Vaadin Board is using link:https://github.com/polymer/polymer/tree/2.0-preview[Polymer 2].

= Features

- Allows to divide you layout into regions by using [elementname]#vaadin-board-row#.
- Layout is responsive - rearranges child elements based on available space.
- Supports nested regions.

= Internet Explorer 11 & Safari 9 support

Vaadin Board is using Polymer 2 and ES6. To support IE11 and Safari 9 you need to transpile ES6 to ES5.
The easiest way to do that, is using link:https://www.polymer-project.org/2.0/docs/tools/polymer-cli#build[Polymer CLI].
Add a build configuration to your link:https://www.polymer-project.org/2.0/docs/tools/polymer-json[polymer.json]:

[source, html]
----
  "builds": [{
    "name": "my-app",
    "js": {"minify": true, "compile": true},
    "css": {"minify": true},
    "html": {"minify": true}
  }]
----
Running [command]`polymer build` in you application folder will create a traspiled version of your application.
Your application will be transpiled and saved in build folder.

Another option to transpile ES6 to ES5 is to use link:https://babeljs.io/[Babel].

= Known Issues

- Because non-chrome browsers need to load a polyfill, you can see flickering, before definition of the web component comes in.
You can suspend rendering the component before it is ready by adding the `unresolved` attribute in body:

[source, html]
----
  <body unresolved>
   //Your code here
  </body>
----

- Because Vaadin Board uses flexbox, there is a limited support for IE11.
If you want to have a border for the direct child of the [elementname]#vaadin-board-row# you need to create a wrapper
[elementname]#div# and add a border there, but not to the direct child of the [elementname]#vaadin-board-row#.
The description of the bug can be found link:https://github.com/philipwalton/flexbugs#7-flex-basis-doesnt-account-for-box-sizingborder-box[here].

