---
title: Overview
order: 1
layout: page
---

[[board.overview]]
= Overview

The [elementname]#vaadin-board# is a Polymer element for creating flexible responsive layouts and building nice looking dashboards.
The [elementname]#vaadin-board# key feature is how it effectively reorders the widgets on different screen sizes, maximizing the use of space and looking stunning.
Vaadin Board is using link:https://github.com/polymer/polymer/tree/2.0-preview[Polymer 2].

[[board.features]]
= Features

- Four and three columns based layout for laying out things the way you like it.
- Responsive design, works on all screen sizes, it rearranges child elements based on available space.
- Element responsiveness. Not only is the component itself responsive, but each row reacts individually to the space given to it in a responsive way.
- Allows to divide your layout into regions by using vaadin-board-row.
- `board-cols` attribute makes one widget flow over multiple slots. This way you can build row configurations where for example you have one widget that takes 75% of the space and another that takes 25%, 25-50-25 or 33-67. 
- Supports nested regions. You can put a new row within another row to build how ever complex layouts that you want in a simple way.

