language: java
jdk: openjdk8
dist: xenial

script:
  - if mvn dependency:tree | grep -B3 "version selected from constraint"; then
      echo "Error. Have found versions that are selected from constraint, pin those so they won't change themselves.";
      exit 1;
    fi;
  - xvfb-run  --server-args="-screen 0 1024x768x24" mvn -B clean verify -Dvaadin.productionMode -Dcom.vaadin.testbench.Parameters.testsInParallel=2 -Dvaadin.proKey=$VAADIN_PRO_KEY -Dsauce.user=$SAUCE_USER -Dsauce.sauceAccessKey=$SAUCE_ACCESSKEY 

#deploy:
#  - provider: script
#    script: ./.travis.deploy.sh
#    skip_cleanup: true
#    on:
#      branch: master

# Cache requires a master build
branches:
  only:
    - master
    - /^\d+\.\d+$/

cache:
  directories:
  - $HOME/.m2

before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/vaadin-app-layout-flow
