language: java
jdk: openjdk8
dist: xenial
before_install:
  - echo "sauce.user=$SAUCE_USER" > local.properties && echo "sauce.sauceAccessKey=$SAUCE_ACCESSKEY" >> local.properties

script: xvfb-run  --server-args="-screen 0 1024x768x24" mvn -B clean verify -Dvaadin.proKey=$VAADIN_PRO_KEY -Dvaadin.productionMode -Dcom.vaadin.testbench.Parameters.testsInParallel=2

branches:
  only:
    - master
    - /^\d+\.\d+$/
cache:
  directories:
  - $HOME/.m2

before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/vaadin-cookie-consent-flow

