// Types for the Flow-specific menu bar API, including the private
// @vaadin/menu-bar API that the connector relies on. The public API types
// come from the @vaadin npm packages, resolved from the integration tests
// module's node_modules (see tsconfig.json in the module root).
import type { MenuBar } from '@vaadin/menu-bar/src/vaadin-menu-bar.js';
// The context menu connector generates the items, so their types come from
// that module, resolved through the rootDirs in tsconfig.json
import type {
  FlowContextMenuItem,
  FlowContextMenuItemComponent
} from '../vaadin-context-menu/vaadin-context-menu-types.js';
import type { MenuBarConnector } from './menubarConnector.js';

export type { MenuBarConnector };

/** A menu item element in the Flow DOM tree, e.g. `vaadin-menu-bar-item` */
export type FlowMenuBarItemComponent = FlowContextMenuItemComponent;

/** An item generated by the context menu connector's `generateItemsTree` */
export type FlowMenuBarItem = FlowContextMenuItem;

/**
 * The private @vaadin/menu-bar API and the Flow-specific API that the menu
 * bar connector relies on
 */
export interface FlowMenuBarInternals {
  $connector: MenuBarConnector;
  items: FlowMenuBarItem[];
  /** The buttons container, absent until the web component's first render */
  _container: HTMLElement | undefined;
}

/** The Flow menu bar element */
export type FlowMenuBar = Omit<MenuBar, 'items'> & FlowMenuBarInternals;

declare global {
  // Adds to the Flow namespace declared by the context menu module
  interface VaadinFlow {
    menubarConnector: {
      initLazy(menuBar: FlowMenuBar, appId: string): void;
    };
  }
}
