// Types for the Flow-specific menu bar API, including the private
// @vaadin/menu-bar API that the connector relies on. The public API types
// come from the @vaadin npm packages, resolved from the integration tests
// module's node_modules (see tsconfig.json in the module root).
import type { MenuBar } from '@vaadin/menu-bar/src/vaadin-menu-bar.js';
import type { MenuBarConnector } from './menubarConnector.js';

export type { MenuBarConnector };

/** A menu item element in the Flow DOM tree, e.g. `vaadin-menu-bar-item` */
export interface FlowMenuBarItemComponent extends HTMLElement {
  disabled?: boolean;
  /**
   * The root-level item generated for the component. Kept separately from
   * `_item`, which the web component reassigns when the button goes to the
   * overflow menu.
   */
  _rootItem?: FlowMenuBarItem;
  /** The item generated for the component by the context menu connector */
  _item?: FlowMenuBarItem;
}

/** An item generated by the context menu connector's `generateItemsTree` */
export interface FlowMenuBarItem {
  component: FlowMenuBarItemComponent;
  disabled?: boolean;
  className?: string;
  children?: FlowMenuBarItem[];
}

/**
 * The private @vaadin/menu-bar API and the Flow-specific API that the menu
 * bar connector relies on
 */
export interface FlowMenuBarInternals {
  $connector: MenuBarConnector;
  items: FlowMenuBarItem[];
  /** The buttons container, absent until the web component's first render */
  _container: HTMLElement | undefined;
}

/** The Flow menu bar element */
export type FlowMenuBar = Omit<MenuBar, 'items'> & FlowMenuBarInternals;

declare global {
  // Augments the global Vaadin interface declared by @vaadin/component-base
  // with the Flow namespace used by the connector
  interface Vaadin {
    Flow: {
      menubarConnector: {
        initLazy(menuBar: FlowMenuBar, appId: string): void;
        setClassName(component: FlowMenuBarItemComponent): void;
      };
      /** Provided by the context menu module's contextMenuConnector.js */
      contextMenuConnector: {
        generateItemsTree(appId: string, nodeId: number): FlowMenuBarItem[] | undefined;
      };
    };
  }
}
