// Types for the Flow-specific context menu API, including the private
// @vaadin/context-menu API that the connector relies on. The public API types
// come from the @vaadin npm packages, resolved from the integration tests
// module's node_modules (see tsconfig.json in the module root).
//
// The menu bar module reuses the item types from here, so this file must not
// import from a file with a module augmentation, which would then be missing
// from that module's compilation.
import type { ContextMenu } from '@vaadin/context-menu/src/vaadin-context-menu.js';
import type { ContextMenuConnector } from './contextMenuConnector.js';

export type { ContextMenuConnector };

/**
 * A menu item element in the Flow DOM tree, e.g. `vaadin-context-menu-item` or
 * `vaadin-menu-bar-item`, with the state Flow sets on it
 */
export interface FlowContextMenuItemComponent extends HTMLElement {
  disabled?: boolean;
  tooltip?: string;
  tooltipPosition?: string;
  _checked?: boolean;
  _keepOpen?: boolean;
  __theme?: string;
  /** Set by the item mixin, tells a menu item apart from any other component */
  _hasVaadinItemMixin?: boolean;
  /** The node id of the container holding the item's sub menu items */
  _containerNodeId?: number;
  /** The item generated for the component by the connector */
  _item?: FlowContextMenuItem;
}

/**
 * An item generated by the connector's `generateItemsTree`. The state
 * properties are getters reading from the item component, so they always
 * reflect the current element state. The sub menu is also read through a
 * getter, resolved on the first read once the item component has a container
 * node id, and cached from then on.
 */
export interface FlowContextMenuItem {
  component: FlowContextMenuItemComponent;
  readonly checked?: boolean;
  readonly keepOpen?: boolean;
  readonly disabled?: boolean;
  readonly className?: string;
  readonly theme?: string;
  readonly tooltip?: string;
  readonly tooltipPosition?: string;
  readonly children?: FlowContextMenuItem[];
}

/**
 * The private @vaadin/context-menu API and the Flow-specific API that the
 * context menu connector relies on
 */
export interface FlowContextMenuInternals {
  $connector?: ContextMenuConnector;
  items?: FlowContextMenuItem[];
}

/** The Flow context menu element */
export type FlowContextMenu = Omit<ContextMenu, 'items'> & FlowContextMenuInternals;

/** The context menu connector API registered on the Flow namespace */
export interface ContextMenuConnectorApi {
  initLazy(contextMenu: FlowContextMenu, appId: string): void;
  generateItemsTree(appId: string, nodeId: number): FlowContextMenuItem[] | undefined;
  setChecked(component: FlowContextMenuItemComponent, checked: boolean): void;
}

declare global {
  // Augments the global Vaadin interface declared by @vaadin/component-base
  // with the Flow namespace used by the connector. The namespace is a shared
  // interface that each module merges its own members into, so that connectors
  // from different modules can be type-checked in the same program.
  interface Vaadin {
    Flow: VaadinFlow;
  }

  interface VaadinFlow {
    contextMenuConnector: ContextMenuConnectorApi;
    /** The store of Flow DOM nodes, keyed by app id */
    clients: Record<string, VaadinFlowClient>;
  }

  /** The Flow client of an app instance on the page */
  interface VaadinFlowClient {
    getByNodeId(nodeId: number): HTMLElement | null;
  }
}
