language: java
jdk: openjdk8
dist: xenial

script: mvn -B clean verify -Dvaadin.productionMode -Dcom.vaadin.testbench.Parameters.testsInParallel=2 -Dvaadin.proKey=$VAADIN_PRO_KEY -Dsauce.user=$SAUCE_USER -Dsauce.sauceAccessKey=$SAUCE_ACCESSKEY

#deploy:
#  - provider: script
#    script: ./.travis.deploy.sh
#    skip_cleanup: true
#    on:
#      branch: master

# Cache requires a master build
branches:
  only:
    - master
    - /^\d+\.\d+$/
cache:
  directories:
  - $HOME/.m2

before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/vaadin-confirm-dialog-flow

